* About rclone_jobber.sh
rclone_jobber.sh is a shell script to make backups.
It performs a backup job by calling rclone.
Rclone is a mature tool and many [[https://github.com/ncw/rclone/wiki/Third-Party-Integrations-with-rclone][third party tools use rclone]].

rclone_jobber.sh has been tested on Linux, and should also run on macOS and [[https://docs.microsoft.com/en-us/windows/wsl/about][Windows 10 wsl]].
An [[file:rclone_jobber_tutorial.org][rclone_jobber_tutorial]] includes backup-job and restore-job examples for a home computer.

*rclone_jobber.sh features:*
- Options to archive old backup files in their original hierarchy
- Abort if job is already running (maybe previous run didn't finish)
- Pop-up for error conditions
- Option for a cron-monitoring service
- Logging
- POSIX compliant
- Free (open source Creative Commons Zero license)

*Rclone features:*
- Back up to remote cloud storage (safe from local disaster)
- Over 30 cloud-storage providers to choose from (so you're never locked into a provider)
- Back up to local storage
- Optional encryption (Crypt)
- MD5/SHA1 hashes checked at all times for file integrity
- Timestamps preserved on files
- Filter rules (to exclude or include files)
- rsync-like algorithm and interface
- Sync (one way) mode to make a directory identical
- Partial syncs supported on a whole file basis
- Free (open source MIT license)

Both rclone and rclone_jobber.sh are command line tools.
If you prefer a GUI, checkout [[https://mmozeiko.github.io/RcloneBrowser/][RcloneBrowser]].

* Non-Linux operating systems
rlcone_jobber.sh is a shell script.
Shell scripts can run on Linux, macOS, and [[https://docs.microsoft.com/en-us/windows/wsl/about][Windows 10 wsl]].

rlcone_jobber.sh has been tested on Linux.
rlcone_jobber.sh uses notify-send, which is a popup notification on most Linux desktops.
If you test rlcone_jobber.sh on a non-linux operating system, please post your results on https://github.com/wolfv6/rclone_jobber/issues.

* Contact
Submit issues to https://github.com/wolfv6/rclone_jobber/issues.

Pull requests are welcome.

* Licenses
[[http://creativecommons.org/licenses/by-nc-sa/4.0/][https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]\\
The content of the tutorial, including associated setup_test_data_directory.sh, are licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 license.

[[http://creativecommons.org/publicdomain/zero/1.0/][http://i.creativecommons.org/p/zero/1.0/88x31.png]]\\
rclone_jobber.sh source code, including associated job files, filter_rules file, and test_suite, are licensed under the Creative Commons Zero 1.0 license.

Rclone_jobber is not affiliated with rclone.
